# Generated by fusen: do not edit by hand


#' Title
#'
#' @param dataset a dataset with column primary_fur_color that the function will check
#'
#' @return outputs message in the console to specify if the integrity check was successful 
#' @export
#'
check_data_integrity <- function(dataset){
  if(any(grepl("\\+", dataset[, "primary_fur_color"]))) {
    stop("primary_fur_color does not contain unique colors")
  } else {
    message("data integrity check ok")
  }
}

